// Stub for Microsoft.AspNetCore.App

// semmle-extractor-options: Microsoft.AspNetCore.Http.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Razor.Runtime.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.CommandLine.cs
// semmle-extractor-options: Microsoft.AspNetCore.Metadata.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.cs
// semmle-extractor-options: Microsoft.Extensions.Hosting.cs
// semmle-extractor-options: Microsoft.AspNetCore.Authorization.Policy.cs
// semmle-extractor-options: Microsoft.Extensions.Diagnostics.HealthChecks.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.Cors.cs
// semmle-extractor-options: Microsoft.AspNetCore.Cors.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.EnvironmentVariables.cs
// semmle-extractor-options: Microsoft.AspNetCore.SignalR.Core.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.Abstractions.cs
// semmle-extractor-options: Microsoft.Extensions.Options.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.Core.cs
// semmle-extractor-options: Microsoft.Extensions.Hosting.Abstractions.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.Binder.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.Ini.cs
// semmle-extractor-options: Microsoft.AspNetCore.Authentication.OAuth.cs
// semmle-extractor-options: System.IO.Pipelines.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.Razor.cs
// semmle-extractor-options: Microsoft.Extensions.Identity.Core.cs
// semmle-extractor-options: Microsoft.Extensions.Localization.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.HostFiltering.cs
// semmle-extractor-options: Microsoft.Extensions.Caching.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Localization.cs
// semmle-extractor-options: System.Windows.Extensions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Server.HttpSys.cs
// semmle-extractor-options: System.Security.Cryptography.Xml.cs
// semmle-extractor-options: Microsoft.Extensions.Identity.Stores.cs
// semmle-extractor-options: Microsoft.AspNetCore.Http.Connections.Common.cs
// semmle-extractor-options: Microsoft.AspNetCore.Authentication.Cookies.cs
// semmle-extractor-options: Microsoft.AspNetCore.Antiforgery.cs
// semmle-extractor-options: Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.TagHelpers.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.KeyPerFile.cs
// semmle-extractor-options: Microsoft.AspNetCore.Components.Web.cs
// semmle-extractor-options: Microsoft.AspNetCore.Components.Authorization.cs
// semmle-extractor-options: Microsoft.AspNetCore.SignalR.Protocols.Json.cs
// semmle-extractor-options: Microsoft.Extensions.DependencyInjection.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.EventLog.cs
// semmle-extractor-options: System.Security.Cryptography.Cng.cs
// semmle-extractor-options: Microsoft.AspNetCore.Routing.cs
// semmle-extractor-options: Microsoft.AspNetCore.Http.Features.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.FileExtensions.cs
// semmle-extractor-options: Microsoft.AspNetCore.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.Xml.cs
// semmle-extractor-options: Microsoft.AspNetCore.SignalR.Common.cs
// semmle-extractor-options: System.Diagnostics.EventLog.cs
// semmle-extractor-options: Microsoft.Extensions.Options.DataAnnotations.cs
// semmle-extractor-options: Microsoft.AspNetCore.Diagnostics.HealthChecks.cs
// semmle-extractor-options: Microsoft.AspNetCore.Http.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.ApiExplorer.cs
// semmle-extractor-options: Microsoft.AspNetCore.Html.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Authentication.cs
// semmle-extractor-options: Microsoft.AspNetCore.ResponseCaching.cs
// semmle-extractor-options: Microsoft.AspNetCore.Hosting.Server.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.DataProtection.Extensions.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.cs
// semmle-extractor-options: Microsoft.AspNetCore.Authentication.Core.cs
// semmle-extractor-options: Microsoft.AspNetCore.ResponseCaching.Abstractions.cs
// semmle-extractor-options: Microsoft.Win32.Registry.cs
// semmle-extractor-options: System.Security.AccessControl.cs
// semmle-extractor-options: System.Security.Permissions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.DataAnnotations.cs
// semmle-extractor-options: Microsoft.Extensions.Localization.cs
// semmle-extractor-options: Microsoft.AspNetCore.DataProtection.cs
// semmle-extractor-options: Microsoft.AspNetCore.Identity.cs
// semmle-extractor-options: Microsoft.Extensions.ObjectPool.cs
// semmle-extractor-options: Microsoft.AspNetCore.Diagnostics.cs
// semmle-extractor-options: Microsoft.JSInterop.cs
// semmle-extractor-options: Microsoft.AspNetCore.Components.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.Console.cs
// semmle-extractor-options: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.cs
// semmle-extractor-options: Microsoft.Extensions.Http.cs
// semmle-extractor-options: Microsoft.AspNetCore.Cryptography.KeyDerivation.cs
// semmle-extractor-options: Microsoft.AspNetCore.Server.Kestrel.cs
// semmle-extractor-options: Microsoft.AspNetCore.StaticFiles.cs
// semmle-extractor-options: Microsoft.Extensions.FileProviders.Composite.cs
// semmle-extractor-options: Microsoft.AspNetCore.Hosting.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.RazorPages.cs
// semmle-extractor-options: Microsoft.AspNetCore.Razor.cs
// semmle-extractor-options: Microsoft.Extensions.FileProviders.Abstractions.cs
// semmle-extractor-options: System.Security.Principal.Windows.cs
// semmle-extractor-options: Microsoft.AspNetCore.Session.cs
// semmle-extractor-options: Microsoft.AspNetCore.DataProtection.Abstractions.cs
// semmle-extractor-options: Microsoft.Extensions.Options.ConfigurationExtensions.cs
// semmle-extractor-options: Microsoft.Extensions.DependencyInjection.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.WebUtilities.cs
// semmle-extractor-options: Microsoft.AspNetCore.Http.Connections.cs
// semmle-extractor-options: Microsoft.Extensions.WebEncoders.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.Debug.cs
// semmle-extractor-options: Microsoft.AspNetCore.Server.IIS.cs
// semmle-extractor-options: Microsoft.AspNetCore.SignalR.cs
// semmle-extractor-options: Microsoft.Extensions.FileProviders.Physical.cs
// semmle-extractor-options: Microsoft.AspNetCore.Routing.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.ResponseCompression.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.TraceSource.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.ViewFeatures.cs
// semmle-extractor-options: Microsoft.AspNetCore.Server.Kestrel.Core.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.cs
// semmle-extractor-options: Microsoft.AspNetCore.Rewrite.cs
// semmle-extractor-options: Microsoft.AspNetCore.Authorization.cs
// semmle-extractor-options: Microsoft.Net.Http.Headers.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.Abstractions.cs
// semmle-extractor-options: Microsoft.Extensions.Caching.Memory.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.Configuration.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.Formatters.Xml.cs
// semmle-extractor-options: Microsoft.Extensions.Primitives.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.UserSecrets.cs
// semmle-extractor-options: Microsoft.AspNetCore.HttpOverrides.cs
// semmle-extractor-options: Microsoft.AspNetCore.Server.IISIntegration.cs
// semmle-extractor-options: Microsoft.AspNetCore.HttpsPolicy.cs
// semmle-extractor-options: Microsoft.AspNetCore.Hosting.cs
// semmle-extractor-options: Microsoft.Extensions.FileSystemGlobbing.cs
// semmle-extractor-options: Microsoft.AspNetCore.Mvc.Localization.cs
// semmle-extractor-options: Microsoft.AspNetCore.Components.Server.cs
// semmle-extractor-options: Microsoft.AspNetCore.CookiePolicy.cs
// semmle-extractor-options: Microsoft.AspNetCore.Authentication.Abstractions.cs
// semmle-extractor-options: Microsoft.Extensions.FileProviders.Embedded.cs
// semmle-extractor-options: Microsoft.AspNetCore.Components.Forms.cs
// semmle-extractor-options: Microsoft.Extensions.Configuration.Json.cs
// semmle-extractor-options: Microsoft.AspNetCore.Diagnostics.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.WebSockets.cs
// semmle-extractor-options: Microsoft.AspNetCore.Http.Extensions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Connections.Abstractions.cs
// semmle-extractor-options: Microsoft.AspNetCore.Localization.Routing.cs
// semmle-extractor-options: Microsoft.Extensions.Logging.EventSource.cs
